version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: nest_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user_admin:password123@db:5432/nest_db
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
      build:
        context: ./client
        dockerfile: Dockerfile
      container_name: next_client
      restart: always
      ports:
        - "3001:3000" # Acceso desde http://localhost:3001
      environment:
        - NEXT_PUBLIC_API_URL=http://localhost:3000
      depends_on:
        - app

volumes:
  pgdata:
